#!/bin/sh

if which svnversion >/dev/null; then
  # svnversion exists
  myVersion=`svnversion`
  base_repo=`svn info | egrep '^URL' | sed -e 's/^URL: *//g' -e 's#.*/##g'`
  if echo $myVersion | grep -qe '[0-9]' ; then
    # There is a number in the version, so probably it makes sense
    echo -DREVISIONNUMBER=\"${base_repo}/${myVersion}\"
  fi
fi
