#!/bin/sh

if which svnversion >/dev/null; then
  # svnversion exists
  myVersion=`svnversion`
  if echo $myVersion | grep -qe '[0-9]' ; then
    # There is a number in the version, so probably it makes sense
    echo -DREVISIONNUMBER=\"$myVersion\"
  fi
fi
